# Generated by Django 4.1.7 on 2023-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournaments',
            options={'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AlterModelOptions(
            name='tournamentsrules',
            options={'verbose_name_plural': 'Tournaments Rules'},
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='closeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='openDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
