# Generated by Django 4.1.7 on 2023-02-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tournaments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
