# Generated by Django 4.1.7 on 2023-02-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tournaments_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('openDate', models.DateField(blank=True, null=True)),
                ('closeDate', models.DateField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Camps',
            },
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('openDate', models.DateField(blank=True, null=True)),
                ('closeDate', models.DateField(blank=True, null=True)),
                ('img', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='LeaguesRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leagues')),
            ],
            options={
                'verbose_name_plural': 'Leagues Rules',
            },
        ),
        migrations.CreateModel(
            name='CampsRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(blank=True, null=True)),
                ('camps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camps')),
            ],
            options={
                'verbose_name_plural': 'Camps Rules',
            },
        ),
    ]
