# Generated by Django 4.1.7 on 2023-03-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_camps_leagues_leaguesrules_campsrules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campsrules',
            old_name='camps',
            new_name='camp',
        ),
    ]
