# Generated by Django 4.1.7 on 2023-03-01 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_rename_camps_campsrules_camp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentsRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('capital_first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('capital_last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tournaments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguesRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('capital_first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('capital_last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leagues')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampsRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_first_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('parent_last_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.camps')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampsChildRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_full_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('child_age', models.IntegerField(blank=True, null=True)),
                ('camp_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campsregister')),
            ],
        ),
    ]
