# Generated by Django 4.1.7 on 2023-03-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tournamentsregister_leaguesregister_campsregister_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguesregister',
            old_name='capital_first_name',
            new_name='captain_first_name',
        ),
        migrations.RenameField(
            model_name='leaguesregister',
            old_name='capital_last_name',
            new_name='captain_last_name',
        ),
        migrations.RenameField(
            model_name='tournamentsregister',
            old_name='capital_first_name',
            new_name='captain_first_name',
        ),
        migrations.RenameField(
            model_name='tournamentsregister',
            old_name='capital_last_name',
            new_name='captain_last_name',
        ),
    ]
