# Generated by Django 4.1.7 on 2023-03-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_capital_first_name_leaguesregister_captain_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campschildregister',
            old_name='child_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='campschildregister',
            old_name='child_full_name',
            new_name='name',
        ),
    ]
