# Generated by Django 4.1.7 on 2023-03-12 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_child_age_campschildregister_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('rebounds', models.IntegerField(blank=True, null=True)),
                ('assets', models.IntegerField(blank=True, null=True)),
                ('leagues_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leaguesregister')),
            ],
        ),
    ]
