# Generated by Django 4.1.7 on 2023-03-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_leagueteammembers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaguesregister',
            options={'verbose_name_plural': 'League Team Registration'},
        ),
        migrations.CreateModel(
            name='LeagueTeamStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('loses', models.IntegerField(blank=True, null=True)),
                ('leagues_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leaguesregister')),
            ],
        ),
    ]
