# Generated by Django 4.1.7 on 2023-03-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_leagueschedule_leagues_register_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leagueteamstats',
            old_name='loses',
            new_name='losses',
        ),
    ]
