# Generated by Django 4.1.7 on 2023-03-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_loses_leagueteamstats_losses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leagueteammembers',
            old_name='assets',
            new_name='assists',
        ),
    ]
