# Generated by Django 4.1.7 on 2023-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_assets_leagueteammembers_assists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueteammembers',
            name='assists',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueteammembers',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='leagueteammembers',
            name='rebounds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
