# Generated by Django 4.1.7 on 2023-03-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_leagueteammembers_assists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueteamstats',
            name='leagues_register',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.leaguesregister'),
        ),
    ]
