# Generated by Django 4.1.7 on 2023-03-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_leagueteamstats_leagues_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueschedule',
            name='league',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.leagues'),
        ),
    ]
